- name: Demo on simple playbook
  hosts: all
  tasks:
    - name: task1
      ansible.builtin.debug:
        msg: Hello from Play task1
    - name: task2
      ansible.builtin.debug:
        msg: Hello from Play task2